version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Exclude node_modules from being mounted
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true 